[project]
authors = ["Gianluca Della Vedova <gianluca@dellavedova.org>"]
channels = ["conda-forge", "bioconda"]
name = "CV"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bibtexparser = ">=1.4.3,<2"
jupyterlab = ">=4.3.6,<5"
black = ">=25.1.0,<26"
